apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: divas-pvc
  labels:
    app: assignment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  
  storageClassName: ebs-sc
  volumeMode: Filesystem